import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  superCartContainer: {
    height: 'auto',
    width: windowWidth * 0.95,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginTop: windowHeight * 0.03,
  },
  firstContainer: {
    backgroundColor: '#fff',
    alignSelf: 'center',
    height: windowHeight * 0.3,
    width: windowWidth * 0.95,
    borderTopLeftRadius: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: windowHeight * 0.03,
  },
  firstContainerInformation: {
    backgroundColor: '#fff',
    alignSelf: 'center',
    paddingTop: windowHeight * 0.03,
    paddingBottom: windowHeight * 0.03,
    width: windowWidth * 0.95,
    borderTopLeftRadius: 30,
    borderRadius: 8,
    // marginTop: windowHeight * 0.03,
  },
  panierVide: {
    alignSelf: 'center',
    height: windowHeight * 0.3,
    width: windowWidth * 0.95,
    borderTopLeftRadius: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: windowHeight * 0.03,
  },
  secondContainer: {
    backgroundColor: '#fff',
    alignSelf: 'center',
    height: windowHeight * 0.08,
    width: windowWidth * 0.95,
    borderRadius: 8,
    // borderBottomRightRadius: 30,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: windowHeight * 0.015,
    flexDirection: 'row',
  },
  firstRow: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    alignSelf: 'center',
  },
  secondRow: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    alignSelf: 'center',
  },
  thirdRow: {
    // backgroundColor: 'tomato',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.8,
    alignSelf: 'center',
  },
  coounterContainer: {
    // backgroundColor: 'gold',
    flexDirection: 'row',
    height: windowHeight * 0.1,
    width: windowWidth * 0.3,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  WeightCalText: {
    color: '#000',
    fontSize: 17,
    fontFamily: 'Poppins-Medium',
    textAlign: "center",
    marginBottom: 10
  },
  WeightCalSubText: {
    color: '#3F4C58',
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
  },
  counterTExt: {
    fontSize: 26,
    color: 'gray',
  },
  counterButton: {
    width: 40,
    height: 40,
    borderRadius: 100,
    backgroundColor: '#DFE8F2',
    elevation: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterButtonText: {
    color: '#A1B0C1',
    fontSize: 20,
  },
  cartIcon: {
    // backgroundColor: 'green',
    width: windowWidth * 0.06,
    height: 25,
  },
  cartText: {
    color: 'gray',
    fontSize: 14,
    fontFamily: 'Roboto-Bold',
    fontWeight:'600',
    // backgroundColor: 'tomato',
    marginLeft: 10,
    width: windowWidth * 0.4,
  },
  cartshshText: {
    color: '#000',
    textAlign: 'center',
    fontSize: 12,
    fontFamily: 'Roboto-Regular',
  },
  cartsubText: {
    color: '#8998A8',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  cartContaineer: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: windowWidth * 0.25,
    height: windowHeight * 0.05,
  },
  buttonContaineer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: windowWidth * 0.5,
    height: windowHeight * 0.05,
    backgroundColor: '#fff',
    borderRadius: 10,
    elevation: 1,
  },
  discountCodeInputStyle: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.35,
    height: 'auto',
    fontFamily: 'Roboto-Regular',
    color: '#000',
    textAlignVertical: 'center',
    fontSize: 12,
  },
  priceText: {
    fontFamily: 'Roboto-Bold',
    fontSize: 12,
    color: '#000',
  },
  safeContainerStyle: {
    justifyContent: 'center',
    width: windowWidth * 0.8,
    alignSelf: 'center',
    marginTop: windowHeight * 0.02,
  },
  totalContainer: {
    // backgroundColor: 'green',
    alignSelf: 'center',
    // height: windowHeight * 0.08,
    width: windowWidth * 0.8,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: windowHeight * 0.01,
    flexDirection: 'row',
  },
  avoirContainer: {
    // backgroundColor: 'green',
    alignSelf: 'center',
    // height: windowHeight * 0.08,
    width: windowWidth * 1.2,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: windowHeight * 0.01,
    flexDirection: 'row',
  },
  totalText: {
    fontSize: 17,
    fontFamily: 'Roboto-Bold',
    color: '#3F4C58',
    // backgroundColor: 'tomato',
  },
  btnContainer: {
    backgroundColor: '#3292E0',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: windowHeight * 0.01,
    width: windowWidth * 0.8,
    height: windowHeight * 0.07,
    borderRadius: 40,
    marginBottom: 20,
  },
  btnText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },
  ButtonContainer: {
    width: 250,
    height: 45,
    borderRadius: 60,
    justifyContent: 'center',
    backgroundColor: '#3292E0',
    marginTop: '25%',
    alignSelf: 'center',
    marginBottom: 10,
  },
  ButtonText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 14,
    fontFamily: 'Roboto-Regular',
  },
  btnClearBasket:{
    marginTop:15,
    marginLeft:'70%'
  },
  btnClearBasketText:{
    textAlign:'left',
    color: '#3292E0',
    fontSize: 14,
    fontFamily: 'Roboto-Bold',
  },
  paysLivraisonText:{
    textAlign:'center',
    color: '#3292E0',
    fontSize: 14,
    fontFamily: 'Roboto-Bold',
    marginTop:15
  },
  selectedTextStyle: {
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    color: '#14213D',
    borderColor: "#d5d6d7"
  },
  containerDepotStyle: {
    backgroundColor: '#fff',
    borderRadius: 8,
    maxHeight: 100,
    borderColor: "transparent"
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  containerStyle: {
    backgroundColor: '#d5d6d7',
    borderRadius: 8,
    maxHeight: 100,
  },
  dropdown: {
    height: 50,
    borderRadius: 8,
    paddingHorizontal: 17,
    backgroundColor: '#d5d6d7',
    borderColor: "transparent"
  },
  placeholderStyle: {
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    color: '#14213D',
  },
  dropContainerStyle: {
    justifyContent: 'center',
    // backgroundColor: 'tomato',
    width: windowWidth * 0.8,
    // borderRadius:0
    alignSelf: 'center',
    marginTop: windowHeight * 0.02,
    marginBottom: windowHeight * 0.01,
  },
  containerrrrStyle: {
    marginTop: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
    maxHeight: 100,
    elevation: 10,
  },
});

export default styles;
