import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  containerSafee: {
    flex: 1,
    backgroundColor: '#fff',
    marginTop: 20,
  },
  containerStyle: {
    width: '100%',
    backgroundColor: '#fff',
    marginTop: windowHeight * 0.05,
  },
  spacerStyle: {},
  safeContainerStyle: {
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    // backgroundColor: 'tomato',
    marginBottom: windowHeight * 0.1,
  },
  ButtonContainer: {
    width: '100%',
    height: 50,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#000',
    marginTop: windowHeight * 0.015,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  ButtonText: {
    marginLeft: '5%',
    width: '100%',
    color: '#AFAFAF',
    fontSize: windowWidth * 0.035,
    fontFamily: 'Poppins-Regular',
  },
  CountrySelect: {
    width: '80%',
    alignSelf: 'center',
    height: 48,
    borderColor: '#DADAED',
    borderWidth: 1,
    backgroundColor: '#fff',
    marginTop: 5,
    borderRadius: 7,
    flexDirection: 'row',
    marginBottom: 30,
  },
  InputNam: {
    marginLeft: '3%',
    fontSize: 15,
    fontFamily: 'Roboto-Regular',
    width: windowWidth * 0.65,
    // backgroundColor: 'gold',
    flex: 1,
    color: '#000',
  },
  ButtonStyle: {
    width: '80%',
    borderRadius: 60,
    justifyContent: 'center',
    backgroundColor: '#4E8FDA',
    alignSelf: 'center',
    paddingVertical: 8,
    paddingHorizontal: 20,
  },
  ButtonStyleText: {
    textAlign: 'center',
    color: 'white',
    fontSize: windowWidth * 0.036,
    fontFamily: 'Roboto-Regular',
    lineHeight: 20,
  },
  TotalContainer: {
    flexDirection: 'row',
    width: windowWidth * 0.8,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-around',
    // backgroundColor: 'tomato',
    marginBottom: windowHeight * 0.02,
  },
  TotalText: {
    width: '30%',
    fontSize: 18,
    fontFamily: 'Roboto-Regular',
    color: '#1C1939',
  },
  PriceText: {
    width: '68%',
    fontSize: 18,
    fontFamily: 'Roboto-Regular',
    textAlign: 'right',
    color: '#1C1939',
  },
  domicileStyle: {
    fontFamily: 'Roboto-Regular',
    fontSize: 18,
    textAlign: 'center',
    color: '#1C1939',
  },
  Heading: {
    fontSize: 18,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
    color: '#1C1939',
  },
  subHeading: {
    fontSize: 16,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
    color: '#1C1939',
  },
  SecondHeading: {
    fontSize: 18,
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    marginTop: 25,
    marginBottom: 15,
    color: '#1C1939',
  },
  inputCountryCustomContainer: {
    backgroundColor: '#fff',
    width: windowWidth * 0.8,
    height: 52,
    alignSelf: 'center',
    justifyContent: 'flex-start',
    paddingLeft: 15,
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 7,
  },
  inputCustomDropdownContainer: {
    width: windowWidth * 0.8,
    alignSelf: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 30,
  },
  phoneContainer: {
    // width: '75%',
    width: windowWidth * 0.7,
    height: 50,
    backgroundColor: '#fff',
    elevation: 0,
    // backgroundColor: 'tomato',
  },
  countryPickerContainerStyle: {
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 3,
  },
  textInput: {
    backgroundColor: 'transparent',
    paddingVertical: 0,
    // backgroundColor: 'gold',
    width: windowWidth * 0,
    backgroundColor: '#fff',
    fontFamily: 'Roboto-Regular',
    color: '#000',
  },
  codeTextStyle: {
    fontFamily: 'Roboto-Regular',
    fontSize: 15,
    // backgroundColor: 'green',
    width: 'auto',
  },
  countryPickerButtonStyle: {
    // backgroundColor: 'gold',
    width: 50,
  },
  textInputStyle: {
    fontFamily: 'Roboto-Regular',
    color: '#000',
  },
  dropContainerStyle: {
    justifyContent: 'center',
    // backgroundColor: 'tomato',
    width: windowWidth * 0.01,
    // borderRadius:0
    alignSelf: 'center',
    marginTop: windowHeight * 0.02,
    marginBottom: windowHeight * 0.01,
  },

  dropdown: {
    height: 54,
    borderRadius: 8,
    paddingHorizontal: 17,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#000',
    // elevation: 1,
    width: windowWidth * 0.85,
    // borderWidth: 1,
    // borderColor: '#DADAED',
    alignSelf: 'center',
  },
  placeholderStyle: {
    fontSize: windowWidth * 0.035,
    fontFamily: 'Poppins-Regular',
    color: '#14213D',
  },
  selectedTextStyle: {
    fontSize: 16,
    fontFamily: 'Roboto-Regular',
    color: '#14213D',
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  containerrrrStyle: {
    marginTop: 0,
    backgroundColor: '#fff',
    borderRadius: 8,
    maxHeight: 180,
    elevation: 10,
  },
  containerDepotStyle: {
    backgroundColor: '#fff',
    borderRadius: 8,
    maxHeight: 250,
    elevation: 10,
  },

  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    width: windowWidth * 0.9,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    paddingVertical: 8,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#4E8FDA',
    color: '#4E8FDA',
    borderRadius: 25,
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: '#4E8FDA',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    color: '#000',
  },
});

export default styles;
