import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  tabsContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 1.0,
    height: windowHeight * 0.05,
    flexDirection: 'column',
    // alignItems: 'center',
    // justifyContent: 'space-around',
    //  alignSelf: 'center',
    position: 'absolute',
    top: windowHeight * 0.1,
  },
  tabNameContainer: {
    // backgroundColor: 'green',
    borderBottomColor: '#fff',
    // borderBottomWidth: 2,
  },
  tabarTextStyle: {
    fontFamily: 'Roboto-Regular',
    fontSize: 12,
    color: '#fff',
    marginLeft: windowWidth * 0.1,
    paddingTop: windowHeight * 0.01,
    borderBottomWidth: 1,
    borderBottomColor: '#fff',
  },
  selectCountryTextStyle: {
    fontFamily: 'Roboto-Regular',
    fontSize: 12,
    color: '#fff',
    paddingLeft: windowWidth * 0.1,
    paddingTop: windowHeight * 0.01,
  },
  headerStyle: {
    backgroundColor: '#3292E0',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 280,
    borderBottomEndRadius: 250,
    borderBottomLeftRadius: 250,
    transform: [{scaleX: 1.3}],
    zIndex: 1,
  },
  mainTextStyle: {
    fontFamily: 'Roboto-Bold',
    fontSize: 14,
    color: '#fff',
  },
  INContainer: {
    width: 100,
    height: windowHeight * 0.1,
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
    // backgroundColor: 'tomato',
    alignSelf: 'center',
    marginLeft: 170,
    marginRight: 140,
    // marginTop: 60,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    textAlign: 'center',
    color: 'red',
    fontSize: 16,
    marginTop: 20,
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: 10,
  },
  dropdown: {
    height: 40,
    width: windowWidth * 0.4,
    borderRadius: 8,
    backgroundColor: '#FFF',
    paddingHorizontal: 10,
  },
  filterButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  sortItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  sortItemText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    color: '#000',
  },
  scrollView: {
    flex: 1,
  },
  productListContainer: {
    paddingBottom:
      Platform.OS === 'ios' ? windowHeight * 0.1 : windowHeight * 0.05,
  },
  imageStyler: {
    width: windowWidth * 0.14,
    height: windowHeight * 0.09,
  },
  subTabbarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderRadius: 5,
    marginTop: windowWidth * 0.01,
    alignSelf: 'center',
    // padding: 10,
    // marginBottom: 10,
  },
  subTabbarContainerFilter: {
    height: windowHeight * 0.055,
    width: windowWidth * 0.95,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
    alignSelf: 'center',
    elevation: 5,
    justifyContent: 'center',
  },
  subTabbarScrollContainer: {
    alignSelf: 'center',
    // backgroundColor: 'tomato',
    width: 'auto',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginLeft: 20,
    paddingRight: 20,
  },
  iconStyler: {
    width: 20,
    height: 20,
    alignSelf: 'center',
    // backgroundColor: 'green',
  },
  textActive: {
    color: '#376AED',
  },
  text: {
    color: '#616162',
  },
  imageTextContainer: {
    flexDirection: 'row',
    height: windowHeight * 0.065,
    alignItems: 'center',
    gap: 2,
    // margin: 5,
  },
  tabsContainer: {
    width: windowWidth * 1.0,
    height: windowHeight * 0.05,
    flexDirection: 'column',
    position: 'absolute',
    top: windowHeight * 0.1,
  },
  tabarTextStyle: {
    fontFamily: 'Roboto-Regular',
    fontSize: 12,
    color: '#fff',
    marginLeft: windowWidth * 0.1,
    paddingTop: windowHeight * 0.01,
    borderBottomWidth: 1,
    borderBottomColor: '#fff',
  },
  filterTextContainer: {
    flexDirection: 'row',
    height: windowHeight * 0.035,
    alignItems: 'center',
    justifyContent: 'space-around',
    width: windowWidth * 0.15,
    backgroundColor: '#fff',
    elevation: 3,
    borderRadius: 5,
    margin: windowWidth * 0.01,
  },
  filterTextStyle: {
    fontFamily: 'Roboto-Regular',
    fontSize: 10,
    color: '#000',
    width: windowWidth * 0.2,
    height: windowHeight * 0.035,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontWeight: 'bold',
  },
  subtabarTextStyle: {
    fontFamily: 'Roboto-Regular',
    fontSize: windowWidth * 0.02,
    color: '#000',
    // backgroundColor: 'gold',
    height: windowHeight * 0.035,
    textAlign: 'center',
    // textAlignVertical: 'center',
  },
  widthBig: {
    width: windowWidth * 0.3,
  },
  widthShort: {
    width: windowWidth * 0.25,
  },
  widthTextBig: {
    width: windowWidth * 0.2,
  },
  widthTextShort: {
    width: windowWidth * 0.16,
  },
  marginTopBig: {
    marginTop: windowWidth * 0.05,
  },
  marginTopShort: {
    marginTop: windowWidth * 0.035,
  },
  upperRow: {
    // backgroundColor: 'green',
    flexDirection: 'row',
    height: windowHeight * 0.1,
    width: windowWidth * 0.95,
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: windowHeight * 0.03,
  },
});

export default styles;
