import {Dimensions, Platform, StyleSheet} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    // justifyContent: 'center',
  },
  signupHeaderText: {
    fontFamily: 'Roboto-Regular',
    fontSize: 23,
    marginTop: windowHeight * 0.1,
    color: '#fff',
  },
  signupView: {
    flex: 1,
    width: windowWidth * 1,
    height: windowHeight * 0.7,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Platform.OS === 'ios' ? windowHeight * 0.12 : windowWidth * 0.16,
  },
  inputCustomContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.7,
    // height: windowHeight * 0.09,
    marginBottom: 15,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorMessageTextStyle: {
    color: 'red',
    textAlign: 'left',
    // marginTop: Platform.OS === 'ios' ? -10 : -13,
    width: windowWidth * 0.66,
    fontFamily: 'Roboto-Regular',
    fontSize: 12,
  },
  inputCustomLogoContainer: {
    // backgroundColor: 'tomato',
    width: windowWidth * 0.7,
    height: windowHeight * 0.07,
    marginTop: 10,
    alignSelf: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputCountryCustomContainer: {
    width: windowWidth * 0.8,
    marginTop: 2,
  },
  inputCustom: {
    // backgroundColor: 'tomato',
    borderWidth: 1,
    borderColor: '#AAB0B7',
    paddingLeft: 15,
    borderRadius: 8,
    fontFamily: 'Poppins-Regular',
    color: '#000',
    height: 54,
    width: windowWidth * 0.8,
    marginBottom: 12,
    fontSize: 14,
    color: '#000',
    backgroundColor: '#fff',
  },
  inputCountryCustom: {
    // backgroundColor: 'tomato',
    color: '#000',
    width: windowWidth * 0.4,
    fontSize: 16,

    fontFamily: 'Roboto-Regular',
  },
  Auth1: {
    backgroundColor: '#3292E0',
    borderRadius: 50,
    width: windowWidth * 0.8,
    height: windowHeight * 0.08,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: windowHeight * 0.02,
    elevation: 2,
    marginTop: windowHeight * 0.03,
  },
  AuthButtonText: {
    color: '#fff',
    fontFamily: 'Roboto-Regular',
  },
  agreeTermTextContainer: {
    marginTop: windowWidth * 0.02,
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: windowWidth * 0.02,
    // backgroundColor: 'tomato',
    width: '100%',
    maxWidth: windowWidth * 0.8,
    alignSelf: 'center',
    flexDirection: 'row',
  },
  agreeMax: {
    flex: 1,
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
  },
  agreeTermText: {
    color: '#838391',
    fontSize: 12,
    fontFamily: 'Roboto-Regular',
    textAlign: 'left',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 50,
  },

  agreeTermUSeText: {
    color: '#3292E0',
    fontSize: 12,
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
  },
  phoneContainer: {
    // width: '75%',
    width: windowWidth * 0.83,
    height: 50,
    backgroundColor: '#fff',
    flexDirection: 'row',
    marginBottom: 12,
    alignItems: 'center',
    gap: 5,
    color: '#000',
    backgroundColor: 'transparent',
  },
  textInput: {
    backgroundColor: 'transparent',
    padding: 0,
    // backgroundColor: 'gold',
    width: windowWidth * 0.6,
    color: '#000',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
  },
  codeTextStyle: {
    fontFamily: 'Roboto-Regular',
    fontSize: 15,
    // backgroundColor: 'gold',
    // width: windowWidth * 0.1,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  countryPickerButtonStyle: {
    // backgroundColor: 'gold',
    width: 70,
  },
  textInputStyle: {
    fontFamily: 'Roboto-Regular',
    color: '#000',
  },
  checkboxContainer: {
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  checkbox: {
    zIndex: 1000,
    alignSelf: 'center',
    width: 20,
    height: 20,
    marginRight: 10,
  },
  label: {
    margin: 8,
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    color: '#000',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    width: '80%',
  },
  codeInput: {
    borderWidth: 1,
    borderColor: '#AAB0B7',
    borderRadius: 8,
    padding: 10,
    marginBottom: 20,
  },
  sendCodeButton: {
    backgroundColor: '#4E8FDA',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    marginBottom: 10,
  },
  sendCodeButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  closeButton: {
    padding: 10,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#4E8FDA',
  },
  countryPickerContainerStyle: {
    borderRadius: 8,
    paddingVertical: Platform.OS === 'ios' ? 8 : 3,
  },

  textInput: {
    textAlignVertical: 'center',
  },
});

export default styles;
